{
  "comments": [
    {
      "key": {
        "uuid": "5aeda501_e2970820",
        "filename": "resources/libraries/python/PapiExecutor.py",
        "patchSetId": 1
      },
      "lineNbr": 327,
      "author": {
        "id": 76
      },
      "writtenOn": "2019-09-06T16:04:20Z",
      "side": 1,
      "message": "I realize that these retries will be problem for Async",
      "range": {
        "startLine": 319,
        "startChar": 1,
        "endLine": 327,
        "endChar": 60
      },
      "revId": "132b86e570c78c10f2c2151b34ab639aff7267d6",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": true
    }
  ]
}