{
  "comments": [
    {
      "key": {
        "uuid": "da141535_99c01b2c",
        "filename": "resources/libraries/python/InterfaceUtil.py",
        "patchSetId": 1
      },
      "lineNbr": 525,
      "author": {
        "id": 207
      },
      "writtenOn": "2016-04-28T12:56:42Z",
      "side": 1,
      "message": "Please, correct allignment:\nraise RuntimeError(\u0027Create loopback failed on node \"{}\"\u0027\n                   .format(node[\u0027host\u0027]))",
      "range": {
        "startLine": 524,
        "startChar": 12,
        "endLine": 525,
        "endChar": 30
      },
      "revId": "badbd9a841672daf6563fdf6c8ecddf38ddb0bef",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": false
    }
  ]
}