{
  "comments": [
    {
      "key": {
        "uuid": "11fa5f2e_70a67e73",
        "filename": "resources/libraries/python/TrafficGenerator.py",
        "patchSetId": 54
      },
      "lineNbr": 445,
      "author": {
        "id": 1263
      },
      "writtenOn": "2019-08-23T14:37:08Z",
      "side": 1,
      "message": "Ok rebase error but not visible, as it is a lack of edit.\nLine 438 should set stdout. (I guess visible as pylint error now.)",
      "range": {
        "startLine": 445,
        "startChar": 36,
        "endLine": 445,
        "endChar": 42
      },
      "revId": "ff02566ce95a6c4450d2b053f2c3745592b71fc9",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": true
    }
  ]
}